
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - name: show az version
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az version
            
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI
      uses: Azure/cli@1.0.4
      with:
        inlineScript: |
            AZURE_RG

      # Deploy Bicep file
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      id: arm-deploy
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./done.json
        parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        failOnStdErr: false
